// Hostinger Passenger Entry Point
// This dynamically loads the highly-optimized Next.js standalone server
// automatically generated by `output: "standalone"` in next.config.ts

const path = require('path');
const fs = require('fs');

const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

if (fs.existsSync(standaloneServerPath)) {
    console.log('> Starting Official Next.js Standalone Server on Hostinger');
    require(standaloneServerPath);
} else {
    console.error('FATAL: .next/standalone/server.js not found!');
    console.error('Make sure you have run "npm run build" with "output: standalone" in next.config.ts');
    process.exit(1);
}
